#!/usr/bin/env python
import pandas as pd
import os
import glob

# Check required input arguments.
if config["inputs"]["singularity_image"] is None or not os.path.exists(config["inputs"]["singularity_image"]):
    logger.error("Critical, singularity_image does not exist.\n\nExiting.")
    exit("MissingsingularityImage")
if config["inputs"]["repo_dir"] is None or not os.path.exists(config["inputs"]["repo_dir"]):
    logger.error("Critical, repo_dir does not exist.\n\nExiting.")
    exit("MissingRepoDir")
if config["outputs"]["output_dir"] is None:
    logger.error("Critical, the output_dir cannot be empty.\n\nExiting.")
    exit("MissingOutputDir")

# Add trailing /.
if not config["outputs"]["output_dir"].endswith("/"):
    config["outputs"]["output_dir"] += "/"

# Create the output directory.
os.makedirs(config["outputs"]["output_dir"], exist_ok=True)

# Create batches
n_batch = config["settings"]["batches"]
batches = list(range(1,n_batch+1))

def get_sample_ids(cell_type):
  dir = config["outputs"]["output_dir"] + "correlations/data/" + cell_type + "/"
  files = glob.glob(os.path.join(dir, '*.corr.done'))
  sample_ids = set()
  return list(sample_ids)

rule all:
  input: 
    merged_coeqtls = expand(config["outputs"]["output_dir"] + "coeQTL/output/{cell_type}/{cell_type}--TopEffects.txt", cell_type=config["settings"]["cell_type"],allow_missing=True)

rule create_linkfile:
  input: config["inputs"]["sample_list"]
  output: config["outputs"]["output_dir"] + "coeQTL/reffiles/{cell_type}/linkfile.txt"
  resources:
    mem_per_thread_gb = lambda wildcards, attempt: attempt * config["create_linkfile_memory"],
    disk_per_thread_gb = lambda wildcards, attempt: attempt * config["create_linkfile_memory"],
    time = lambda wildcards,attempt: config["cluster_time"][(attempt - 1) + config["create_linkfile_time"]]
  threads: config["create_linkfile_threads"]
  params:
    bind = config["inputs"]["bind_path"],
    sif = config["inputs"]["singularity_image"],
    script =  config["inputs"]["repo_dir"] + "scripts/create_linkfile.py",
    wg0_file_directories = config["inputs"]["wg0_file_directories"],
    out = config["outputs"]["output_dir"] + "coeQTL/reffiles/{cell_type}/"
  log: config["outputs"]["output_dir"] + "log/{cell_type}/create_linkefile.{cell_type}.log"
  shell:
    """
    singularity exec --bind {params.bind} {params.sif} python {params.script} \
      --sample_ids {input} \
      --wg0_file_directories {params.wg0_file_directories}\
      --out {params.out}
    """

rule get_significant_eqtls:
  input: config["inputs"]["top_effects"],
  output: config["outputs"]["output_dir"] + "coeQTL/reffiles/{cell_type}/{cell_type}-significant_eqtls.txt"
  resources:
    mem_per_thread_gb = lambda wildcards, attempt: attempt * config["get_significant_eqtls_threads"],
    disk_per_thread_gb = lambda wildcards, attempt: attempt * config["get_significant_eqtls_threads"],
    time = lambda wildcards,attempt: config["cluster_time"][(attempt - 1) + config["get_significant_eqtls_time"]]
  threads: config["get_significant_eqtls_threads"]
  params:
    bind = config["inputs"]["bind_path"],
    sif = config["inputs"]["singularity_image"],
    script =  config["inputs"]["repo_dir"] + "scripts/determine_significant_eqtl_snp_gene_pairs.py"
  log: config["outputs"]["output_dir"] + "log/{cell_type}/get_significant_eqtls.{cell_type}.log"
  shell:
    """
    singularity exec --bind {params.bind} {params.sif} python {params.script} {input} {output}
    """

rule get_gene_pairs:
  input: config["inputs"]["co_expr_dir"] + "correlations/data/{cell_type}/chr{chr}/{cell_type}.chr.{chr}.corr.transpose.stripped.txt.gz"
  output: config["outputs"]["output_dir"] + "coeQTL/reffiles/{cell_type}/chr{chr}/genepairs.txt"
  resources:
    mem_per_thread_gb = lambda wildcards, attempt: attempt * config["get_gene_pairs_memory"],
    disk_per_thread_gb = lambda wildcards, attempt: attempt * config["get_gene_pairs_memory"],
    time = lambda wildcards,attempt: config["cluster_time"][(attempt - 1) + config["get_gene_pairs_time"]]
  threads: config["get_gene_pairs_threads"]
  params:
    bind = config["inputs"]["bind_path"],
    sif = config["inputs"]["singularity_image"],
    script =  config["inputs"]["repo_dir"] + "scripts/get_gene_pairs.py",
    out = config["outputs"]["output_dir"] + "coeQTL/reffiles/{cell_type}/chr{chr}/"
  log: config["outputs"]["output_dir"] + "log/{cell_type}/get_gene_pairs.{cell_type}.chr.{chr}.log"
  shell:
    """
    singularity exec --bind {params.bind} {params.sif} {params.script} --input {input} --out {params.out}
    """

rule create_snp_gene_pair_triplet:
  input: 
    significant_eqtls = config["outputs"]["output_dir"] + "coeQTL/reffiles/{cell_type}/{cell_type}-significant_eqtls.txt",
    gene_pairs = config["outputs"]["output_dir"] + "coeQTL/reffiles/{cell_type}/chr{chr}/genepairs.txt"
  output: 
    triplet = config["outputs"]["output_dir"] + "coeQTL/reffiles/{cell_type}/chr{chr}/snp_genepair_triplets_to_test.txt",
    triplet_group = config["outputs"]["output_dir"] + "coeQTL/reffiles/{cell_type}/chr{chr}/snp_genepair_triplets_to_test_groups.txt"
  resources:
    mem_per_thread_gb = lambda wildcards, attempt: attempt * config["create_snp_gene_pair_triplet_memory"],
    disk_per_thread_gb = lambda wildcards, attempt: attempt * config["create_snp_gene_pair_triplet_memory"],
    time = lambda wildcards,attempt: config["cluster_time"][(attempt - 1) + config["create_snp_gene_pair_triplet_time"]]
  threads: config["create_snp_gene_pair_triplet_threads"]
  params:
    bind = config["inputs"]["bind_path"],
    sif = config["inputs"]["singularity_image"],
    script =  config["inputs"]["repo_dir"] + "scripts/create_snp_genepair_triplet_list.py"
  log: config["outputs"]["output_dir"] + "log/{cell_type}/create_snp_gene_pair_triplet.{cell_type}.chr.{chr}.log"
  shell:
    """
    singularity exec --bind {params.bind} {params.sif} python {params.script} \
      {input.significant_eqtls} \
      {wildcards.chr} \
      {input.gene_pairs} \
      {output.triplet} \
      {output.triplet_group}
    """

rule create_annotation:
  input: 
    gene_pairs = config["outputs"]["output_dir"] + "coeQTL/reffiles/{cell_type}/chr{chr}/genepairs.txt",
    gene_annotation = config["inputs"]["gene_annotation"]
  output: 
    annotation = config["outputs"]["output_dir"] + "coeQTL/reffiles/{cell_type}/chr{chr}/annotation.txt.gz"
  resources:
    mem_per_thread_gb = lambda wildcards, attempt: attempt * config["create_annotation_memory"],
    disk_per_thread_gb = lambda wildcards, attempt: attempt * config["create_annotation_memory"],
    time = lambda wildcards,attempt: config["cluster_time"][(attempt - 1) + config["create_annotation_time"]]
  threads: config["create_annotation_threads"]
  params:
    bind = config["inputs"]["bind_path"],
    sif = config["inputs"]["singularity_image"],
    script =  config["inputs"]["repo_dir"] + "scripts/createAnnotation.py"
  log: config["outputs"]["output_dir"] + "log/{cell_type}/create_annotation.{cell_type}.chr.{chr}.log"
  shell:
    """
    singularity exec --bind {params.bind} {params.sif} python {params.script} \
      {input.gene_pairs} \
      {input.gene_annotation} \
      {output.annotation}
    """

rule filter_genotype:
  input:
    top_effects = config["inputs"]["top_effects"],
    genotype = config["inputs"]["genotype"]
  output:
    filtered_genotype = config["outputs"]["output_dir"] + "coeQTL/reffiles/{cell_type}/{cell_type}.eqtlsnps.bgz.vcf.gz"
  resources:
    mem_per_thread_gb = lambda wildcards, attempt: attempt * config["filter_genotype_memory"],
    disk_per_thread_gb = lambda wildcards, attempt: attempt * config["filter_genotype_memory"],
    time = lambda wildcards,attempt: config["cluster_time"][(attempt - 1) + config["filter_genotype_time"]] 
  threads: config["filter_genotype_threads"]
  params:
    bind = config["inputs"]["bind_path"],
    sif = config["inputs"]["singularity_image"],
    script_dir =  config["inputs"]["repo_dir"] + "scripts/",
    out = config["outputs"]["output_dir"] + "coeQTL/reffiles/{cell_type}/{cell_type}."
  log: config["outputs"]["output_dir"] + "log/{cell_type}/filter_genotype.{cell_type}.log"
  shell:
    """
    singularity exec --bind {params.bind} {params.sif} python {params.script_dir}filter_genotype.py \
      --top_effects {input.top_effects} \
      --genotype {input.genotype} \
      --output {params.out}eqtlsnps.vcf.gz 

    bash {params.script_dir}compress_vcf.sh {params.out}eqtlsnps.vcf.gz {output.filtered_genotype}
    """

rule create_batches:
  input:
    correlation = config["inputs"]["co_expr_dir"] + "correlations/data/{cell_type}/chr{chr}/{cell_type}.chr.{chr}.corr.transpose.stripped.txt.gz",
    linkfile = config["outputs"]["output_dir"] + "coeQTL/reffiles/{cell_type}/linkfile.txt",
    genotype = config["inputs"]["genotype"],
    gene_pairs = config["outputs"]["output_dir"] + "coeQTL/reffiles/{cell_type}/chr{chr}/genepairs.txt",
    annotation = config["outputs"]["output_dir"] + "coeQTL/reffiles/{cell_type}/chr{chr}/annotation.txt.gz",
    triplet = config["outputs"]["output_dir"] + "coeQTL/reffiles/{cell_type}/chr{chr}/snp_genepair_triplets_to_test.txt",
    triplet_group = config["outputs"]["output_dir"] + "coeQTL/reffiles/{cell_type}/chr{chr}/snp_genepair_triplets_to_test_groups.txt"
  output: 
    batches = expand(config["outputs"]["output_dir"] + "coeQTL/output/{cell_type}/chr{chr}/batches/chr{chr}-batch-{n_batch}.txt",n_batch=batches,allow_missing=True)
  resources:
    mem_per_thread_gb = lambda wildcards, attempt: attempt * config["create_batches_memory"],
    disk_per_thread_gb = lambda wildcards, attempt: attempt * config["create_batches_memory"],
    time = lambda wildcards,attempt: config["cluster_time"][(attempt - 1) + config["create_batches_time"]]
  threads: config["create_batches_threads"]
  params:
    bind = config["inputs"]["bind_path"],
    sif = config["inputs"]["singularity_image"],
    script =  config["inputs"]["repo_dir"] + "scripts/createBatches.py",
    batch_prefix = "{cell_type}-chr{chr}",
    job_template = config["inputs"]["repo_dir"] + "scripts/job_template.sh",
    n_batches = 1000,
    out = config["outputs"]["output_dir"] + "coeQTL/output/{cell_type}/chr{chr}/"
  shell:
    """
    singularity exec --bind {params.bind} {params.sif} python {params.script} \
    {wildcards.cell_type}-chr{wildcards.chr} \
    {input.correlation} \
    {input.linkfile} \
    {input.genotype} \
    {input.gene_pairs} \
    {input.annotation} \
    {input.triplet} \
    {input.triplet_group} \
    {params.job_template} \
    {params.n_batches} \
    {params.out}
    """

rule run_co_eqtl:
  input:
    batch = config["outputs"]["output_dir"] + "coeQTL/output/{cell_type}/chr{chr}/batches/chr{chr}-batch-{n_batch}.txt",
    correlation = config["inputs"]["co_expr_dir"] + "correlations/data/{cell_type}/chr{chr}/{cell_type}.chr.{chr}.corr.transpose.stripped.txt.gz",
    linkfile = config["outputs"]["output_dir"] + "coeQTL/reffiles/{cell_type}/linkfile.txt",
    genotype = config["inputs"]["genotype"],
    gene_pairs = config["outputs"]["output_dir"] + "coeQTL/reffiles/{cell_type}/chr{chr}/genepairs.txt",
    annotation = config["outputs"]["output_dir"] + "coeQTL/reffiles/{cell_type}/chr{chr}/annotation.txt.gz",
    triplet = config["outputs"]["output_dir"] + "coeQTL/reffiles/{cell_type}/chr{chr}/snp_genepair_triplets_to_test.txt",
    triplet_group = config["outputs"]["output_dir"] + "coeQTL/reffiles/{cell_type}/chr{chr}/snp_genepair_triplets_to_test_groups.txt"
  output:
    finished = config["outputs"]["output_dir"] + "coeQTL/output/{cell_type}/chr{chr}/output/chr{chr}-batch-{n_batch}--TopEffects.finished",
    coeqtls = config["outputs"]["output_dir"] + "coeQTL/output/{cell_type}/chr{chr}/output/chr{chr}-batch-{n_batch}--TopEffects.txt"
  resources:
    mem_per_thread_gb = lambda wildcards, attempt: attempt * config["run_co_eqtl_memory"],
    disk_per_thread_gb = lambda wildcards, attempt: attempt * config["run_co_eqtl_memory"],
    time = lambda wildcards,attempt: config["cluster_time"][(attempt - 1) + config["run_co_eqtl_time"]]
  threads: config["run_co_eqtl_threads"]
  log: config["outputs"]["output_dir"] + "log/{cell_type}/create_annotation.{cell_type}.chr.{chr}.batch.{n_batch}.log"
  params:
    bind = config["inputs"]["bind_path"],
    sif = config["inputs"]["singularity_image"],
    threads = 2,
    memory = "3g",
    permutations = config["mbqtl_settings"]["permutations"],
    minobservations = config["mbqtl_settings"]["minobservations"],
    mingenotypecount = config["mbqtl_settings"]["mingenotypecount"],
    jar = "/groups/umcg-biogen/tmp02/tools/MbQTL-1.5.1-SNAPSHOT-jar-with-dependencies.jar",
    out = config["outputs"]["output_dir"] + "coeQTL/output/{cell_type}/chr{chr}/output/chr{chr}-batch-{n_batch}"
  shell:
    """
    singularity exec --bind {params.bind} {params.sif} java -Xmx1500m \
      -Djava.util.concurrent.ForkJoinPool.common.parallelism={params.threads} \
      -Dmaximum.threads={params.threads} \
      -Dthread.pool.size={params.threads} \
      -jar {params.jar} \
      -m mbqtl \
      -a {input.annotation} \
      -e {input.correlation} \
      -g {input.linkfile} \
      -v {input.genotype} \
      --chr {wildcards.chr} \
      --perm {params.permutations} \
      --minobservations {params.minobservations} \
      -gl {input.batch} \
      -o {params.out} \
      --expgroups {input.triplet_group} \
      --mingenotypecount {params.mingenotypecount} \
      --fisherzmeta \
      -sgl {input.triplet}
    """

rule merge_co_eqtls:
  input: 
    finished = expand(config["outputs"]["output_dir"] + "coeQTL/output/{cell_type}/chr{chr}/output/chr{chr}-batch-{n_batch}--TopEffects.finished",chr = config["settings"]["chromosomes"], n_batch = batches,allow_missing=True),
    coeqtls = expand(config["outputs"]["output_dir"] + "coeQTL/output/{cell_type}/chr{chr}/output/chr{chr}-batch-{n_batch}--TopEffects.txt",chr = config["settings"]["chromosomes"], n_batch = batches,allow_missing=True)
  output: 
    merged_coeqtls = config["outputs"]["output_dir"] + "coeQTL/output/{cell_type}/{cell_type}--TopEffects.txt"
  resources:
    mem_per_thread_gb = lambda wildcards, attempt: attempt * config["merge_co_eqtls_memory"],
    disk_per_thread_gb = lambda wildcards, attempt: attempt * config["merge_co_eqtls_memory"],
    time = lambda wildcards,attempt: config["cluster_time"][(attempt - 1) + config["merge_co_eqtls_time"]]
  threads: config["merge_co_eqtls_threads"]
  params:
    bind = config["inputs"]["bind_path"],
    sif = config["inputs"]["singularity_image"],
    script = config["inputs"]["repo_dir"] + "scripts/mergeBatchesOverAllChr.py",
    indir=lambda wildcards: config["outputs"]["output_dir"] + "coeQTL/output/{cell_type}/chr{chr}/output/"
  log: config["outputs"]["output_dir"] + "log/{cell_type}/{cell_type}.merge_co_eqtls.log"
  shell:
    """
    singularity exec --bind {params.bind} {params.sif} python {params.script} {params.indir} {output.merged_coeqtls}
    """